// <auto-generated />
namespace MVC_Shubham.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class prod_app2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prod_app2));
        
        string IMigrationMetadata.Id
        {
            get { return "202303070626246_prod_app2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
